- .github/workflows/staging-tests.yml
- prisma/migrations/20250429204401_add_is_blocked_to_buildings/migration.sql
- prisma/schema.prisma
- prisma/seed.ts
- src/api/backoffice/backoffice.routes.ts
- src/api/backoffice/dashboard/controllers/getBuildingsQuantityController.ts
- src/api/backoffice/dashboard/controllers/getCompaniesQuantityController.ts
- src/api/backoffice/dashboard/controllers/getUsersQuantityController.ts
- src/api/backoffice/dashboard/controllers/index.ts
- src/api/backoffice/dashboard/dashboard.routes.ts
- src/api/backoffice/dashboard/services/dashboardServices.ts
Closes [SE-346](https://easyalert.atlassian.net/browse/SE-346)
[SE-346]: https://easyalert.atlassian.net/browse/SE-346?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolves SE-346"Feat//initial dashboard backoffice apis"

- .github/workflows/production-deploy.yml
- prisma/migrations/20250430121620_add_show_to_resident_to_maintenance_history/migration.sql
- prisma/schema.prisma
- src/api/client/building/services/clientBuildingServices.ts
- src/api/company/categories/maintenance/controllers/editMaintenanceHistory.ts
- src/api/shared/maintenance/services/sharedMaintenanceServices.ts
- src/api/shared/maintenancesReports/services/SharedMaintenanceReportsServices.ts
Closes [SE-348](https://easyalert.atlassian.net/browse/SE-348)
[SE-348]: https://easyalert.atlassian.net/browse/SE-348?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolves SE-348 "Feat//show to resident in maintenance"

- src/api/backoffice/account/companies/controllers/createCompanyAndOwner.ts
- src/api/shared/auth/services/authServices.ts
- src/api/shared/users/user/services/sendEmailConfirmation.ts
Closes [SE-353](https://easyalert.atlassian.net/browse/SE-353)
[SE-353]: https://easyalert.atlassian.net/browse/SE-353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolve SE-353 "Fix//send confirmation after company created"

- src/api/shared/maintenancesReports/controllers/sharedMaintenanceHistoryDetails .ts
Closes [SE-349](https://easyalert.atlassian.net/browse/SE-349)
[SE-349]: https://easyalert.atlassian.net/browse/SE-349?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolve SE-349 "Fix//expired maintenances/"

- src/api/company/categories/maintenance/controllers/editMaintenanceHistory.ts
- src/api/shared/maintenance/services/sharedMaintenanceServices.ts
Closes [SE-349](https://easyalert.atlassian.net/browse/SE-349)
[SE-349]: https://easyalert.atlassian.net/browse/SE-349?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolve SE-349 "Fix//create maintenance when expired"

- src/api/shared/checklists/services/checklistServices.ts
Closes [SE-355](https://easyalert.atlassian.net/browse/SE-355)
[SE-355]: https://easyalert.atlassian.net/browse/SE-355?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolve SE-355 "Fix//checklist midnight last minute dates"

- src/api/company/company.routes.ts
- src/api/company/reports/controllers/updateReportPDFController.ts
- src/api/company/reports/services/findMaintenanceReportPDFById.ts
- src/api/company/reports/services/findTicketReportPDFById.ts
- src/api/company/reports/services/updateMaintenanceReportPDF.ts
Closes [SE-361](https://easyalert.atlassian.net/browse/SE-361)
[SE-361]: https://easyalert.atlassian.net/browse/SE-361?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolve SE-361 "Feat//edit report pdf name"

- src/api/shared/company/services/findCompanyOwner.ts
- src/api/shared/maintenancesReports/controllers/sharedCreateMaintenanceReport.ts
Closes [SE-352](https://easyalert.atlassian.net/browse/SE-352)
[SE-352]: https://easyalert.atlassian.net/browse/SE-352?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolve SE-352 "Fix//maintenance proof report email"

- prisma/migrations/20250509184711_add_checklist_report_pdfs_model/migration.sql
- prisma/schema.prisma
- src/api/company/checklists/checklist.routes.ts
- src/api/company/reports/controllers/generateChecklistReportPDFController.ts
- src/api/company/reports/controllers/listChecklistReportsByCompanyIdController.ts
- src/api/company/reports/services/checklistPDFService.ts
- src/api/company/reports/services/createChecklistReportPDF.ts
- src/api/company/reports/services/findFirstChecklistReportPDF.ts
- src/api/company/reports/services/findFirstTicketReportPDF.ts
- src/api/company/reports/services/findManyChecklistReports.ts
- src/api/company/reports/services/findManyChecklistsForReportPDF.ts
- src/api/company/reports/services/updateChecklistReportPDF.ts
- src/api/shared/checklists/controllers/findChecklistReportController.ts
- src/api/shared/checklists/services/checklistServices.ts
Closes [SE-363](https://easyalert.atlassian.net/browse/SE-363)
[SE-363]: https://easyalert.atlassian.net/browse/SE-363?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolve SE-363 "Feat//improve checklist report"

- src/api/company/reports/services/checklistPDFService.ts
- src/utils/dateTime/setToUTCLastMinuteOfDay.ts
Closes [SE-363](https://easyalert.atlassian.net/browse/SE-363)
[SE-363]: https://easyalert.atlassian.net/browse/SE-363?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolve SE-363 "Feat//add observation to checklist report'

- prisma/migrations/20250512172714_add_company_id_checklist_template/migration.sql
- prisma/schema.prisma
- prisma/seed.ts
- prisma/seedServices/index.ts
- src/api/company/checklists/checklist.routes.ts
- src/api/shared/checklists/controllers/createChecklistController.ts
- src/api/shared/checklists/controllers/deleteChecklistController.ts
- src/api/shared/checklists/controllers/getChecklistsTemplatesController.ts
- src/api/shared/checklists/controllers/updateChecklistController.ts
- src/api/shared/checklists/controllers/updateChecklistTemplateController.ts
- src/api/shared/checklists/services/createChecklist.ts
- src/api/shared/checklists/services/getChecklistsTemplates.ts
- src/api/shared/checklists/services/getChecklistsTemplatesById.ts
- src/api/shared/checklists/services/updateChecklistTemplate.ts
Closes [SE-370](https://easyalert.atlassian.net/browse/SE-370)
[SE-370]: https://easyalert.atlassian.net/browse/SE-370?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolve SE-370 "Feat//view and edit checklist template"

- src/api/shared/company/services/findCompanyOwner.ts
Closes [SE-381](https://easyalert.atlassian.net/browse/SE-381)
[SE-381]: https://easyalert.atlassian.net/browse/SE-381?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolve SE-381 "Fix//send report to company owner" 

- src/api/mobile/mobile.routes.ts
Closes [SE-382](https://easyalert.atlassian.net/browse/SE-382)
[SE-382]: https://easyalert.atlassian.net/browse/SE-382?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolve SE-382 "Feat//static api app version"

- prisma/seed.ts
- prisma/seedServices/index.ts
- src/api/backoffice/account/companies/services/companyServices.ts
- src/api/company/buildings/building/services/buildingServices.ts
Closes [SE-383](https://easyalert.atlassian.net/browse/SE-383)
[SE-383]: https://easyalert.atlassian.net/browse/SE-383?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolve SE-383 "Feat//script block buildings"

- src/api/company/dashboard/services/dashboardServices.ts
Closes [SE-376](https://easyalert.atlassian.net/browse/SE-376)
[SE-376]: https://easyalert.atlassian.net/browse/SE-376?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolve SE-376 "Fix//maintenance report cost"

- src/api/shared/checklists/controllers/createChecklistTemplateController.ts
- src/api/shared/checklists/services/getChecklistsTemplates.ts
Closes [SE-370](https://easyalert.atlassian.net/browse/SE-370)
[SE-370]: https://easyalert.atlassian.net/browse/SE-370?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolve SE-370 "Feat//clone checklist template"

- src/api/company/auth/controllers/authLoginWithCompany.ts
- src/api/shared/auth/services/authServices.ts
- src/api/shared/users/user/services/userServices.ts
Closes [SE-389](https://easyalert.atlassian.net/browse/SE-389)
[SE-389]: https://easyalert.atlassian.net/browse/SE-389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolve SE-389 "Feat//can access checklist and ticket"

- src/api/company/buildings/reports/controllers/generateMaintenanceReportPDF.ts
- src/api/company/reports/services/checklistPDFService.ts
- src/api/company/reports/services/ticketPDFService.ts
Closes [SE-341](https://easyalert.atlassian.net/browse/SE-341)
Closes [SE-358](https://easyalert.atlassian.net/browse/SE-358)
[SE-341]: https://easyalert.atlassian.net/browse/SE-341?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SE-358]: https://easyalert.atlassian.net/browse/SE-358?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolve SE-341 SE-358 "Feat//bigger pictures in reports"

- src/api/company/auth/controllers/authBackofficeCompany.ts
Closes [SE-392](https://easyalert.atlassian.net/browse/SE-392)
[SE-392]: https://easyalert.atlassian.net/browse/SE-392?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolve SE-392 "Fix//user login with more companies"

- prisma/migrations/20250522134345_add_servicer_order_number_maintenance_history/migration.sql
- prisma/schema.prisma
- prisma/seed.ts
- prisma/seedServices/index.ts
- src/api/client/building/services/clientBuildingServices.ts
- src/api/client/building/services/findMaintenanceHistory.ts
- src/api/company/buildings/buildingMaintenances/controllers/editBuildingCategoriesAndMaintenances.ts
- src/api/company/buildings/buildingMaintenances/controllers/types.d.ts
- src/api/company/categories/maintenance/controllers/editMaintenanceHistory.ts
- src/api/mobile/auth/controllers/authMobile.ts
- src/api/mobile/auth/services/authServices.ts
- src/api/shared/calendar/services/SharedCalendarServices.ts
- src/api/shared/maintenance/services/sharedMaintenanceServices.ts
- src/api/shared/maintenance/services/types.d.ts
- src/api/shared/maintenanceHistory/services/getCompanyLastServiceOrder.ts
- src/api/shared/maintenancesReports/controllers/sharedCreateMaintenanceReport.ts
- src/api/shared/maintenancesReports/services/SharedMaintenanceReportsServices.ts
- src/api/shared/occasionalReports/sharedCreateOccasionalMaintenanceReport.ts
- src/utils/scripts/fixMaintenancesHistory.ts
Closes [SE-405](https://easyalert.atlassian.net/browse/SE-405)
[SE-405]: https://easyalert.atlassian.net/browse/SE-405?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolve SE-405 "Feat//service order number maintenance history"

- src/api/client/building/controllers/clientBuildingDetails.ts
- src/api/client/building/services/clientBuildingServices.ts
- src/api/client/listForSelect/controllers/listMaintenanceCategoriesForSelectController.ts
- src/api/shared/company/services/findCompanyByBuildingId.ts
Closes [SE-418](https://easyalert.atlassian.net/browse/SE-418)
[SE-418]: https://easyalert.atlassian.net/browse/SE-418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolve SE-418 "Feat//maintenance plan categories filter"

- src/api/company/reports/services/checklistPDFService.ts
- src/api/company/reports/services/createChecklistReportPDF.ts
- src/api/company/reports/services/findManyChecklistsForReportPDF.ts
Closes SE-[367](https://easyalert.atlassian.net/browse/SE-367)
> Resolve SE-367 "Feat//checklist items in report"

- src/api/shared/checklists/services/checklistServices.ts
Closes [SE-425](https://easyalert.atlassian.net/browse/SE-425)
[SE-425]: https://easyalert.atlassian.net/browse/SE-425?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolve SE-425 "Fix//find checklist bychecklist users"

- src/api/backoffice/dashboard/controllers/getMostActiveCompaniesController.ts
- src/api/backoffice/dashboard/controllers/index.ts
- src/api/backoffice/dashboard/dashboard.routes.ts
- src/api/backoffice/dashboard/services/dashboardServices.ts
Closes [SE-428](https://easyalert.atlassian.net/browse/SE-428)
[SE-428]: https://easyalert.atlassian.net/browse/SE-428?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolve SE-428 "Feat//most active companies dashboard"

- src/api/company/buildings/buildingMaintenances/controllers/editBuildingCategoriesAndMaintenances.ts
- src/api/company/buildings/buildingMaintenances/controllers/types.d.ts
Closes [SE-452](https://easyalert.atlassian.net/browse/SE-452)
[SE-452]: https://easyalert.atlassian.net/browse/SE-452?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolve SE-452 "Fix//edit maintenance in plan"

- src/api/client/building/services/findMaintenanceHistory.ts
- src/api/company/buildings/reports/services/buildingReportsServices.ts
Closes [SE-447](https://easyalert.atlassian.net/browse/SE-447)
[SE-447]: https://easyalert.atlassian.net/browse/SE-447?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolve SE-447 "Feat//search separator kanban report"

- prisma/migrations/20250606135040_show_maintenance_priotirty_always_true/migration.sql
- prisma/schema.prisma
- prisma/seed.ts
- prisma/seedServices/index.ts
- src/api/company/buildings/reports/controllers/generateMaintenanceReportPDF.ts
Closes [SE-438](https://easyalert.atlassian.net/browse/SE-438)
[SE-438]: https://easyalert.atlassian.net/browse/SE-438?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolve SE-438 "Feat//maintenance priority always true"

- src/api/shared/upload/upload.ts
- src/api/shared/upload/uploadMany.ts
- src/utils/messages/handleMulterError.ts
Closes [SE-454](https://easyalert.atlassian.net/browse/SE-454)
[SE-454]: https://easyalert.atlassian.net/browse/SE-454?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolve SE-454 "Feat//improve upload error and file size"

- src/api/backoffice/buildings/building.routes.ts
- src/api/backoffice/buildings/controllers/listBuildings.ts
- src/api/backoffice/buildings/services/findManyBuildings.ts
https://easyalert.atlassian.net/browse/SE-305
> Resolve SE-305 "Feat//building Listing"

- src/api/backoffice/buildings/building.routes.ts
- src/api/backoffice/buildings/controllers/listBuildingsDetails.ts
- src/api/backoffice/buildings/services/searchById.ts
https://easyalert.atlassian.net/browse/SE-307
> Resolve SE-307 "Feat//building details"

- src/api/company/buildings/buildingMaintenances/controllers/editBuildingCategoriesAndMaintenances.ts
Closes [SE-502](https://easyalert.atlassian.net/browse/SE-502)
[SE-502]: https://easyalert.atlassian.net/browse/SE-502?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolve SE-502 "Fix//edit maintenances plan"

- package-lock.json
- package.json
- src/api/backoffice/account/users/controllers/createUser.ts
- src/api/backoffice/account/users/services/registerUser.ts
- src/api/backoffice/account/users/users.routes.ts
https://easyalert.atlassian.net/browse/SE-477
> Resolve SE-477 "Feat//api create individual user backoffice"

- prisma/migrations/20221014124857_initial_migrate/migration.sql
- prisma/migrations/20250626171711_platform_videos_new_schema/migration.sql
- prisma/schema.prisma
- src/api/company/company.routes.ts
- src/api/company/home/controllers/getLastFeaturePlatformVideoController.ts
- src/api/company/home/home.routes.ts
- src/api/shared/platformVideos/services/findManyPlatformVideos.ts
- src/api/shared/tutorials/services/createTutorial.ts
- src/api/shared/tutorials/services/deleteOneTutorial.ts
- src/api/shared/tutorials/services/findManyTutorials.ts
- src/api/shared/tutorials/services/updateOneTutorial.ts
Closes [SE-482](https://easyalert.atlassian.net/browse/SE-482)
[SE-482]: https://easyalert.atlassian.net/browse/SE-482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolve SE-482 "Feat//new plataform videos"

- .eslintrc.json
- package-lock.json
- src/api/company/buildings/reports/controllers/generateMaintenanceReportPDF.ts
- src/utils/aws/downloadFromS3.ts
- src/utils/aws/getImageStreamFromS3.ts
- src/utils/aws/s3Config.ts
- src/utils/aws/uploadPDFToS3.ts
- src/utils/processors/pdfImageProcessor.ts
Closes [SE-518](https://easyalert.atlassian.net/browse/SE-518)
[SE-518]: https://easyalert.atlassian.net/browse/SE-518?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolve SE-518 "Feat//improve maintenaces report generation"

- src/utils/emailTransporter/emailTransporterServices.ts
Closes [SE-503](https://easyalert.atlassian.net/browse/SE-503)
[SE-503]: https://easyalert.atlassian.net/browse/SE-503?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolve SE-503 "Fix/email transporter through gmail"

- src/api/shared/listForSelect/services/listBuildingsForSelect.ts
Closes [SE-532](https://easyalert.atlassian.net/browse/SE-532)
[SE-532]: https://easyalert.atlassian.net/browse/SE-532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolve SE-532 "Feat//list non blocked buildings in filters"

- package-lock.json
- package.json
- src/api/company/buildings/reports/controllers/generateMaintenanceReportPDF.ts
- src/api/company/reports/services/checklistPDFService.ts
- src/api/company/reports/services/ticketPDFService.ts
- src/utils/aws/formattedDownloadFromS3.ts
- src/utils/fs/createFolder.ts
Closes [SE-566](https://easyalert.atlassian.net/browse/SE-566)
[SE-566]: https://easyalert.atlassian.net/browse/SE-566?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolve SE-566 "Feat/improve reports with validations"

- src/api/company/reports/controllers/generateTicketReportPDF.ts
- src/api/company/reports/services/findManyTicketsForReportPDF.ts
- src/utils/filters/handleTicketsFilters.ts
Closes [SE-568](https://easyalert.atlassian.net/browse/SE-568)
[SE-568]: https://easyalert.atlassian.net/browse/SE-568?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolve SE-568 "Fix/ticket reports wrong filters'

- src/api/shared/upload/upload.ts
- src/api/shared/upload/uploadMany.ts
Closes [SE-569](https://easyalert.atlassian.net/browse/SE-569)
[SE-569]: https://easyalert.atlassian.net/browse/SE-569?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolve SE-569 "Feat/enhance upload files"

- .eslintrc.json
- src/api/mobile/auth/auth.routes.ts
- src/api/mobile/auth/controllers/authMobile.ts
- src/api/mobile/auth/services/authServices.ts
Closes [SE-571](https://easyalert.atlassian.net/browse/SE-571)
[SE-571]: https://easyalert.atlassian.net/browse/SE-571?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolve SE-571 "Feat/improve mobile login'

- src/api/client/building/controllers/checkPasswordExistenceController.ts
- src/api/client/building/services/clientBuildingServices.ts
- src/api/company/buildings/building/services/buildingServices.ts
https://easyalert.atlassian.net/browse/SE-596
> Resolve SE-596 "Feat//aVerification of building or company blocked for Client"

- prisma/migrations/20250725114452_initial_guarantee_model/migration.sql
- prisma/migrations/20250725161353_initial_gurantee_model/migration.sql
- prisma/schema.prisma
Closes [SE-598](https://easyalert.atlassian.net/browse/SE-598)
[SE-598]: https://easyalert.atlassian.net/browse/SE-598?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolve SE-598 "Feat/guarantee model"

- src/api/company/buildings/reports/controllers/generateMaintenanceReportPDF.ts
- src/api/company/buildings/reports/services/buildingReportsServices.ts
Closes [SE-584](https://easyalert.atlassian.net/browse/SE-584)
[SE-584]: https://easyalert.atlassian.net/browse/SE-584?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolve SE-584 "Feat/filter by all activities maintenance report"

- src/api/shared/occasionalReports/sharedCreateOccasionalMaintenanceReport.ts
Closes [SE-603](https://easyalert.atlassian.net/browse/SE-603)
[SE-603]: https://easyalert.atlassian.net/browse/SE-603?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolve SE-603 "Feat/se 603/occasional maintenance notification"

- prisma/migrations/20250808173928_company_linked_external_for_bills/migration.sql
- prisma/schema.prisma
- src/api/shared/auth/services/authServices.ts
- src/api/shared/users/accounts/controllers/editCompanyAndOwner.ts
- src/api/shared/users/accounts/controllers/types.d.ts
- src/api/shared/users/accounts/services/sharedCompanyServices.ts
- src/api/shared/users/accounts/services/types.d.ts
- src/api/shared/users/user/services/userServices.ts
Closes [SE-635](https://easyalert.atlassian.net/browse/SE-635)
[SE-635]: https://easyalert.atlassian.net/browse/SE-635?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolve SE-635 "Feat/link external cnpjcpf for bill payment"

- src/api/backoffice/buildings/services/findManyBuildings.ts
https://easyalert.atlassian.net/browse/SE-610
> Resolve SE-610 "Feat//allow search by city"

- src/api/shared/users/accounts/controllers/editCompanyAndOwner.ts
Closes [SE-650](https://easyalert.atlassian.net/browse/SE-650)
> Resolve SE-650 "Fix/empty external linked company data"

- src/api/company/calendar/controllers/listCalendarMaintenances.ts
Closes [SE-648](https://easyalert.atlassian.net/browse/SE-648)
[SE-648]: https://easyalert.atlassian.net/browse/SE-648?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolve SE-648 "Fix/filter selected buildings with permissions"

- src/api/company/buildings/reports/services/buildingReportsServices.ts
- src/api/company/buildings/reports/services/types.d.ts
Closes [SE-647](https://easyalert.atlassian.net/browse/SE-647)
Closes [SE-656](https://easyalert.atlassian.net/browse/SE-656)
[SE-647]: https://easyalert.atlassian.net/browse/SE-647?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SE-656]: https://easyalert.atlassian.net/browse/SE-656?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolve SE-647/SE-656 "Fix/reports filter"

- src/api/company/buildings/building/controllers/listBuilding.ts
- src/api/company/buildings/building/services/buildingServices.ts
- src/api/company/buildings/building/services/types.d.ts
Closes [SE-663](https://easyalert.atlassian.net/browse/SE-663)
[SE-663]: https://easyalert.atlassian.net/browse/SE-663?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolve SE-663 "Feat/filter and order buildings list"

- prisma/seedServices/index.ts
Closes [SE-618](https://easyalert.atlassian.net/browse/SE-618)
[SE-618]: https://easyalert.atlassian.net/browse/SE-618?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolve SE-618 "Feat/apartament building type seed"

- prisma/migrations/20250814184035_remove_syndic_password_from_model/migration.sql
- prisma/schema.prisma
- src/api/client/building/controllers/checkPasswordExistenceController.ts
- src/api/client/building/controllers/validatePasswordController.ts
- src/api/company/buildings/building/controllers/listBuildingDetails.ts
- src/api/company/buildings/building/controllers/updateClientPasswordController.ts
- src/api/company/buildings/building/services/buildingServices.ts
- src/utils/scripts/migrateBuildingToOtherCompany.ts
Closes [SE-662](https://easyalert.atlassian.net/browse/SE-662)
[SE-662]: https://easyalert.atlassian.net/browse/SE-662?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolve SE-662 "Feat/remove responsible password"

- src/api/shared/tickets/controllers/deleteTicketController.ts
https://easyalert.atlassian.net/browse/SE-668
> Resolve SE-668 "Feat//option to delete calls (WS)"

- prisma/migrations/20250822133125_stock_management_models/migration.sql
- prisma/schema.prisma
Closes [SE-677](https://easyalert.atlassian.net/browse/SE-677)
[SE-677]: https://easyalert.atlassian.net/browse/SE-677?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolve SE-677 "Feat/stock management models"

- src/api/company/company.routes.ts
- src/api/company/stock/stock.routes.ts
- src/api/company/stock/stockItemTypes/stockItemTypes.routes.ts
- src/api/shared/stockItemType/controllers/createStockItemTypeController.ts
- src/api/shared/stockItemType/controllers/deleteStockItemTypeController.ts
- src/api/shared/stockItemType/controllers/getStockItemTypeController.ts
- src/api/shared/stockItemType/controllers/putStockItemTypeController.ts
- src/api/shared/stockItemType/services/countStockItemType.ts
- src/api/shared/stockItemType/services/createStockItemType.ts
- src/api/shared/stockItemType/services/deleteStockItemType.ts
- src/api/shared/stockItemType/services/findFirstStockItemType.ts
- src/api/shared/stockItemType/services/findManyStockItemType.ts
- src/api/shared/stockItemType/services/findUniqueStockItemType.ts
- src/api/shared/stockItemType/services/updateStockItemType.ts
Closes [SE-678](https://easyalert.atlassian.net/browse/SE-678)
[SE-678]: https://easyalert.atlassian.net/browse/SE-678?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolve SE-678 "Feat/crud operations for stock items type"

- src/api/company/stock/stock.routes.ts
- src/api/company/stock/stockMovements/stockMovements.routes.ts
- src/api/shared/stockMovement/businessRules/createFirstStockMovement.ts
- src/api/shared/stockMovement/businessRules/removalStockMovement.ts
- src/api/shared/stockMovement/controllers/getStockMovementsController.ts
- src/api/shared/stockMovement/services/countStockMovements.ts
- src/api/shared/stockMovement/services/createStockMovement.ts
- src/api/shared/stockMovement/services/deleteStockMovement.ts
- src/api/shared/stockMovement/services/findManyStockMovements.ts
- src/api/shared/stockMovement/services/updateStockMovement.ts
Closes [SE-680](https://easyalert.atlassian.net/browse/SE-680)
[SE-680]: https://easyalert.atlassian.net/browse/SE-680?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolve SE-680 "Feat/crud operations for stock movements"

- src/api/company/stock/stock.routes.ts
- src/api/company/stock/stockInventory/stockInventory.routes.ts
- src/api/shared/stock/controllers/createStockController.ts
- src/api/shared/stock/controllers/deleteStockController.ts
- src/api/shared/stock/controllers/getStockByIdController.ts
- src/api/shared/stock/controllers/getStockController.ts
- src/api/shared/stock/services/countStock.ts
- src/api/shared/stock/services/createStock.ts
- src/api/shared/stock/services/deleteStock.ts
- src/api/shared/stock/services/findFirstStock.ts
- src/api/shared/stock/services/findManyStock.ts
- src/api/shared/stock/services/findUniqueStock.ts
- src/api/shared/stock/services/updateStock.ts
Closes [SE-681](https://easyalert.atlassian.net/browse/SE-681)
[SE-681]: https://easyalert.atlassian.net/browse/SE-681?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolve SE-681 "Feat/se 681/crud operations for stock itens"

- .eslintrc.json
- src/api/backoffice/account/companies/services/companyServices.ts
https://easyalert.atlassian.net/browse/SE-676
> Resolve SE-676 "Feat//Redflag customers who do not use"

- prisma/migrations/20250902031747_add_show_all_tickets_to_resident_building_model/migration.sql
- prisma/schema.prisma
- src/api/client/building/controllers/clientBuildingDetails.ts
- src/api/client/building/services/clientBuildingServices.ts
- src/api/company/buildings/building/controllers/editBuilding.ts
- src/api/company/buildings/building/controllers/listBuildingDetails.ts
- src/api/company/buildings/building/services/buildingServices.ts
Closes [SE-693](https://easyalert.atlassian.net/browse/SE-693)
[SE-693]: https://easyalert.atlassian.net/browse/SE-693?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Resolve SE-693 "Feat/show tickets to all residents building client"

- prisma/migrations/20250825141634_add_client_type_to_company/migration.sql
- prisma/schema.prisma
- src/api/backoffice/account/companies/controllers/createCompanyAndOwner.ts
- src/api/backoffice/account/companies/services/companyServices.ts
- src/api/backoffice/account/companies/services/types.d.ts
https://easyalert.atlassian.net/browse/SE-685
> Resolve SE-685 "Feat//bring type of building"

- prisma/migrations/20250908120817_add_last_edited_at_to_ticket/migration.sql
- prisma/migrations/20250908122512_add_edited_fields_to_ticket/migration.sql
- prisma/schema.prisma
- src/api/shared/tickets/controllers/updateTicketById.ts
- src/api/shared/tickets/services/ticketServices.ts
https://easyalert.atlassian.net/browse/SE-691
> Resolve SE-691 "Feat//editing information in calls"

- src/api/company/categories/maintenance/controllers/getMaintenancesKanban.ts
https://easyalert.atlassian.net/browse/SE-698
> Resolve SE-698 "Fix//Adjust category search in kanban"

- src/api/company/categories/maintenance/controllers/getMaintenancesKanban.ts
- Fix cantReportExpired to be true when today >= expirationDate
- Change tolerance period calculation to period - 1
- Remove unused canReportHistoryPending variable
- Remove debug console.log
> Fix cantReportExpired logic and adjust tolerance period

- src/api/company/tickets/ticket.routes.ts
- src/api/shared/tickets/controllers/deleteTicketImageController.ts
- src/api/shared/tickets/controllers/uploadTicketImageController.ts
https://easyalert.atlassian.net/browse/SE-659
> Resolve SE-659 "Feat//allow editing attachments in calls"

- src/api/company/buildings/reports/controllers/generateMaintenanceReportPDF.ts
[Link jira](https://easyalert.atlassian.net/browse/SE-710)
> Resolve SE-710 "SE-710/pending-maintences-pdf"

- src/api/company/categories/maintenance/controllers/getMaintenancesKanban.ts
[Link jira](https://easyalert.atlassian.net/browse/SE-751)
> Resolve SE-751 Maintenances order in kanban

- src/api/shared/maintenancesReports/controllers/sharedCreateMaintenanceReport.ts
- src/api/shared/maintenancesReports/controllers/sharedMaintenanceHistoryDetails .ts
[Link jira](https://easyalert.atlassian.net/browse/SE-774)
> Resolve SE-774 Occasional maintenances
